### ISSUE TITLE
没有找到models文件

### ISSUE THREAD

**Issue by yixinchen011** [liuxiaoyu1104/UNIC#1]
raceback (most recent call last):
  File "/home/codeAndData/cyx/UNIC/main.py", line 22, in <module>
    import datasets
  File "/home/codeAndData/cyx/UNIC/datasets/__init__.py", line 13, in <module>
    from .coco import build as build_coco
  File "/home/codeAndData/cyx/UNIC/datasets/coco.py", line 30, in <module>
    from models.QueryQTR.VITGen import TransGen
ModuleNotFoundError: No module named 'models'

**Comment by ImYanghan** [comment]
I have the same problem:
from models.QueryQTR.VITGen import TransGen
ModuleNotFoundError: ModuleNotFoundErrorNo module named 'models': 
No module named 'models'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3906259) of binary

**Comment by liuxiaoyu1104** [comment]
The code has been updated, and previously, a file was missed.
