### ISSUE TITLE
KeyError: '210429'  during testing

### ISSUE THREAD

**Issue by King-king424** [liuxiaoyu1104/UNIC#2]
File "/xxxxx/UNIC/datasets/coco.py", line 78, in __getitem__     
init_crop = self.img_crop_image_index[str(image_id)] 
KeyError: '210429'

**Comment by King-king424** [comment]
![image](https://github.com/liuxiaoyu1104/UNIC/assets/39642013/66fdf02b-1ccb-4c13-894f-96be957c49d8)

**Comment by H4Zzer** [comment]
I also encountered the same problem

**Comment by liuxiaoyu1104** [comment]
I have corrected the code. You can download the instances_train.json and instances_test.json files again.

**Comment by ustczhouyu** [comment]
> I have corrected the code. You can download the instances_train.json and instances_test.json files again.

Do I have to provide a JSON file for inference? How to inference on my own image data without any json file and annotation information？

**Comment by ustczhouyu** [comment]
> File "/xxxxx/UNIC/datasets/coco.py", line 78, in **getitem** init_crop = self.img_crop_image_index[str(image_id)] KeyError: '210429'

Hi, do you know how to inference on my own image data without any json file and annotation information？
